# Generated by Django 3.2.9 on 2022-12-26 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleModel',
            new_name='Article',
        ),
    ]
