# Generated by Django 3.2.9 on 2022-12-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_auther'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='auther',
            field=models.CharField(max_length=30),
        ),
    ]
