# Generated by Django 2.1.5 on 2021-10-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_empinfo_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empinfo',
            name='gender',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
