# Generated by Django 2.1.5 on 2021-10-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_auto_20211004_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='empinfo',
            name='working_time',
            field=models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('E', 'Evening')], default='M', max_length=1),
        ),
    ]
