# Generated by Django 3.2.9 on 2022-11-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('role', models.CharField(choices=[('ST', 'staff'), ('US', 'user')], max_length=2)),
            ],
        ),
    ]
